Step 1: Update System
sudo apt update && sudo apt upgrade -y

Step 2: Create Prometheus User
sudo useradd --no-create-home --shell /bin/false prometheus

Step 3: Create Directories
sudo mkdir /etc/prometheus
sudo mkdir /var/lib/prometheus


Step 4: Download Prometheus
wget https://github.com/prometheus/prometheus/releases/download/v2.52.0/prometheus-2.52.0.linux-amd64.tar.gz
tar xvf prometheus-2.52.0.linux-amd64.tar.gz
cd prometheus-2.52.0.linux-amd64

Step 5: Move Binaries and Set Permissions
sudo cp prometheus /usr/local/bin/
sudo cp promtool /usr/local/bin/
sudo chown prometheus:prometheus /usr/local/bin/prometheus
sudo chown prometheus:prometheus /usr/local/bin/promtool

Step 6: Move Configuration Files
sudo cp -r consoles /etc/prometheus
sudo cp -r console_libraries /etc/prometheus
sudo cp prometheus.yml /etc/prometheus
sudo chown -R prometheus:prometheus /etc/prometheus
sudo chown -R prometheus:prometheus /var/lib/prometheus

Step 7: Create Prometheus Systemd Service
sudo nano /etc/systemd/system/prometheus.service

------------------------------------------------------
[Unit]
Description=Prometheus
Wants=network-online.target
After=network-online.target

[Service]
User=prometheus
Group=prometheus
Type=simple
ExecStart=/usr/local/bin/prometheus \
    --config.file=/etc/prometheus/prometheus.yml \
    --storage.tsdb.path=/var/lib/prometheus/ \
    --web.console.templates=/etc/prometheus/consoles \
    --web.console.libraries=/etc/prometheus/console_libraries

[Install]
WantedBy=multi-user.target
-------------------------------------------------------

Step 8: Start and Enable Prometheus
sudo systemctl daemon-reexec
sudo systemctl daemon-reload
sudo systemctl start prometheus
sudo systemctl enable prometheus


Step 9: Verify Status
sudo systemctl status prometheus

http://<your-server-ip>:9090



Prometheus check in 9090 port is default___:

----------------------------------------------------------------------------------------------------------
